---
title: "qpcr_data"
author: "Reilly Cooper"
date: "9/1/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(rstatix)
```

```{r}
qpcr <- read.csv("~/Desktop/targeted_antibiotics_2017/targeted_antibiotic_datasheets/qpcr_ct_data.csv")
# Check for outliers
ggplot(qpcr, aes(sample, cq)) + geom_point() + facet_wrap(~treatment)

# Remove negative controls
qpcr <- qpcr %>% filter(treatment != "NEG")

qpcr_technical_reps_avg <- qpcr %>% 
  group_by(treatment, gene, sample) %>% 
  summarise(average = mean(cq))

control <- qpcr_technical_reps_avg %>% filter(treatment == "CTRL")
control_means <- control %>% group_by(gene) %>% summarise(mean = mean(average))
control_dct <- control_means$mean[1] - control_means$mean[2]

actin <- qpcr_technical_reps_avg %>% filter(gene == "actin") %>%
  `colnames<-` (c("treatment", "gene", "sample", "actin_ct")) %>%
  ungroup() %>%
  select(treatment, sample, actin_ct)
bac <- qpcr_technical_reps_avg %>% filter(gene == "16s") %>%
  `colnames<-` (c("treatment", "gene", "sample", "bac_ct")) %>%
  ungroup() %>%
  select(treatment, sample, bac_ct)

dct_df <- merge(actin, bac, by=c("treatment", "sample")) %>%
  mutate(dct = bac_ct - actin_ct) %>%
  mutate(ddct = dct - control_dct) %>%
  mutate(fold_change = 2^(-ddct)) %>%
  filter(treatment != "NEG")

dct_df$treatment <- factor(dct_df$treatment, 
                                     levels = c("CTRL", 
                                                "AZT", 
                                                "ERY", 
                                                "SFX", 
                                                "ALL"))

dct_df <- dct_df[-27,] # Removing outlier
dct_aov <- aov(ddct ~ treatment, data = dct_df)
summary(dct_aov)
result_text = "Anova, p = 0.0024"
no_ctrl <- dct_df %>% filter(treatment != "CTRL")

dct_df %>% na.omit() %>% group_by(treatment) %>% summarise(mean = mean(fold_change))

qpcr_results <- ggplot(no_ctrl, aes(treatment, fold_change)) +
  geom_hline(yintercept = 1, linetype = "dashed") +
  geom_boxplot(outlier.shape = NA) +
  geom_jitter(width = 0.05, height = 0, alpha = 0.5) +
  xlab("") +
  ylab("Fold Change") +
  theme_bw() +
  annotate("text", x = 1, y = 3, label = result_text)

ggsave("~/Desktop/targeted_antibiotics_2017/figures/qpcr_results.pdf", qpcr_results, dpi = 300, units = "in", width = 6, height = 6)

qpcr_results
```

